import { useCallback, useEffect, useRef, useState } from 'react'
import { ArrowLeft, Check, Download, Heart, History, LockKeyhole, Play, Pause, Star, X } from 'lucide-react'
import { appendBoard, board, compositionNames, explore, familyNames, randomSeed, refine } from '../domain/generate'
import { canonical, compositions, emptyLocks, families, palettes, validateBrief, type Domain, type Family, type PaletteId, type Recipe, type SavedState } from '../domain/model'
import { heroRecipes } from '../fixtures/hero-recipes'
import { loadFonts } from '../render/fonts'
import { compile, type Scene } from '../render/layout'
import { RendererHost } from '../render/host'
import { capabilities, importJson, png, projectJson, saveBlob, video, type VideoKind } from '../export/files'
import { clearSavedState, readState, writeState } from '../storage/database'

const domains:Domain[]=['color','type','shape','motion']
const domainNames:Record<Domain,string>={color:'色',type:'文字組み',shape:'形',motion:'動き'}
const defaultBrief={title:'余白の、その先。',subtitle:''}
const styleDescriptions:Record<Family,string>={weave:'線と文字が交差',fold:'紙面が開閉',tile:'図形で組む',slice:'文字を切り替える',orbit:'円と文字が巡る',echo:'文字の残像が広がる',current:'大きな色帯が流れる',lattice:'細線が形を結ぶ',glyph:'文字が面になる',monolith:'巨大な文字が迫る',interference:'光学パターンと文字',scatter:'字形が粒子になる'}
const styleOrder:Family[]=['monolith','interference','scatter','current','lattice','glyph','weave','fold','tile','slice','orbit','echo']
const initialBoard=()=>{const hs=heroRecipes();return board([hs[9],hs[10],hs[11],hs[6]].map(r=>({...r,id:crypto.randomUUID(),brief:defaultBrief})),'initial',null,null,'all')}
function initial():SavedState{const b=initialBoard();return{version:1,revision:0,boards:[b],favorites:[],activeBoardId:b.id,exploreCounter:0}}
function Cover({recipe,large=false,register}:{recipe:Recipe;large?:boolean;register:(key:string,el:HTMLCanvasElement|null)=>void}){const key=`${recipe.id}:${large?'large':'small'}`;return <canvas ref={el=>register(key,el)} width={480} height={recipe.format==='square'?480:853} aria-label={`${familyNames[recipe.family]}・${compositionNames[recipe.shape.composition]}「${recipe.brief.title}」のプレビュー`} className="cover"/>}
export default function App(){
  const [data,setData]=useState<SavedState>(()=>initial()),[ready,setReady]=useState(false),[busy,setBusy]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState(''),[saveStatus,setSaveStatus]=useState('準備中'),[allowReset,setAllowReset]=useState(false)
  const [draftTitle,setDraftTitle]=useState('余白の、\nその先。'),[draftSubtitle,setDraftSubtitle]=useState(''),[draftFormat,setDraftFormat]=useState<'square'|'portrait'>('square'),[draftFilter,setDraftFilter]=useState<'all'|Family>('all')
  const [edit,setEdit]=useState<Recipe|null>(null),[panel,setPanel]=useState<'export'|'history'|'favorites'|null>(null),[playing,setPlaying]=useState(!matchMedia('(prefers-reduced-motion: reduce)').matches)
  const [removedFavorite,setRemovedFavorite]=useState<Recipe|null>(null)
  const [frame,setFrame]=useState(0),[size,setSize]=useState<720|1080>(720),[kinds,setKinds]=useState<VideoKind[]>([]),[kind,setKind]=useState<VideoKind|null>(null),[progress,setProgress]=useState(0),[videoBlob,setVideoBlob]=useState<Blob|null>(null),[videoUrl,setVideoUrl]=useState(''),[videoKind,setVideoKind]=useState<VideoKind|null>(null)
  const dataRef=useRef(data),revision=useRef(0),saveChain=useRef(Promise.resolve()),conflicted=useRef(false),skipNextSave=useRef(false),generation=useRef(0),capabilityRequest=useRef(0),cancelExport=useRef(false),dialogRef=useRef<HTMLDialogElement>(null),fileRef=useRef<HTMLInputElement>(null),canvases=useRef(new Map<string,HTMLCanvasElement>()),visible=useRef(new Set<string>()),drawn=useRef(new Set<string>()),observer=useRef<IntersectionObserver|null>(null),host=useRef<RendererHost|null>(null),sceneCache=useRef(new Map<string,Scene>()),channel=useRef<BroadcastChannel|null>(null)
  const previewTime=useRef(0)
  const active=data.boards.find(b=>b.id===data.activeBoardId)??data.boards[0],selected=active.candidates.find(r=>r.id===active.selectedId)??active.candidates[0],shown=edit??selected
  const dirty=draftTitle!==selected.brief.title||draftSubtitle!==selected.brief.subtitle||draftFormat!==selected.format||draftFilter!==active.filter
  const editing=!!edit
  const update=useCallback((fn:(value:SavedState)=>SavedState)=>{setData(current=>{const next=fn(current);dataRef.current=next;return next})},[])
  const register=useCallback((key:string,el:HTMLCanvasElement|null)=>{const previous=canvases.current.get(key);if(previous&&previous!==el)observer.current?.unobserve(previous);if(el){el.dataset.coverKey=key;canvases.current.set(key,el);observer.current?.observe(el)}else{canvases.current.delete(key);visible.current.delete(key);drawn.current.delete(key)}},[])
  useEffect(()=>{const o=new IntersectionObserver(entries=>{for(const entry of entries){const key=(entry.target as HTMLElement).dataset.coverKey;if(!key)continue;if(entry.isIntersecting)visible.current.add(key);else visible.current.delete(key)}},{rootMargin:'120px'});observer.current=o;for(const canvas of canvases.current.values())o.observe(canvas);return()=>{o.disconnect();observer.current=null;visible.current.clear()}},[])
  useEffect(()=>{let live=true;(async()=>{let saved:SavedState|null=null,storageError='';try{saved=await readState()}catch(e){storageError=String(e)}
    const next=saved??dataRef.current,current=next.boards.find(x=>x.id===next.activeBoardId)!
    try{await Promise.all([...current.candidates.map(loadFonts),loadFonts(heroRecipes()[0])]);current.candidates.forEach(compile)}catch(e){if(live){setError(String(e));setSaveStatus('フォント読み込み失敗。再読み込みしてください。')}return}
    if(!live)return;if(saved){skipNextSave.current=true;dataRef.current=saved;setData(saved);revision.current=saved.revision;const r=current.candidates.find(x=>x.id===current.selectedId)!;setDraftTitle(r.brief.title);setDraftSubtitle(r.brief.subtitle);setDraftFormat(r.format);setDraftFilter(current.filter)}
    if(storageError){conflicted.current=true;setAllowReset(true);setError(`${storageError} この端末には保存できません。JSONを保存してください。`);setSaveStatus('保存できません')}
    else setSaveStatus(saved?'保存済み':'未保存');setReady(true)
  })();return()=>{live=false}},[])
  useEffect(()=>{if(!('BroadcastChannel'in window))return;const c=new BroadcastChannel('moving-cover-2026-09-25');channel.current=c;c.onmessage=(event:MessageEvent<number>)=>{if(event.data>revision.current){conflicted.current=true;setSaveStatus('保存できません');setError('別のタブで更新されました。最新を読み込むか、この作品をJSON保存してください。')}};return()=>{c.close();if(channel.current===c)channel.current=null}},[])
  useEffect(()=>{if(!ready||conflicted.current)return;if(skipNextSave.current){skipNextSave.current=false;return}setSaveStatus('保存中…');const snapshot=data;saveChain.current=saveChain.current.then(async()=>{const rev=await writeState(snapshot,revision.current);revision.current=rev;channel.current?.postMessage(rev);setSaveStatus('保存済み')}).catch(e=>{if(String(e).includes('別のタブ'))conflicted.current=true;setSaveStatus('保存できません');setError(String(e)+' JSONで作品を保存できます。')})},[data,ready])
  useEffect(()=>{if(!removedFavorite)return;const timer=setTimeout(()=>setRemovedFavorite(null),5000);return()=>clearTimeout(timer)},[removedFavorite])
  useEffect(()=>{if(!videoBlob){setVideoUrl('');return}const url=URL.createObjectURL(videoBlob);setVideoUrl(url);return()=>URL.revokeObjectURL(url)},[videoBlob])
  useEffect(()=>{const p=new RendererHost();host.current=p;let live=true,tick=0,raf=0,working=false,last=0,clockNow:number|null=null
    const loop=async(now:number)=>{if(!live)return;raf=requestAnimationFrame(loop);if(!ready||document.hidden||panel||busy.startsWith('動画')){clockNow=null;return}if(working||now-last<(playing?32:250))return;last=now;working=true
      if(playing){if(clockNow!==null)previewTime.current=(previewTime.current+(now-clockNow)/1000)%6;clockNow=now}else clockNow=null
      try{const b=dataRef.current.boards.find(x=>x.id===dataRef.current.activeBoardId)!;const r=b.candidates.find(x=>x.id===b.selectedId)!;const items=[...b.candidates.map(v=>({recipe:v,key:`${v.id}:small`})),{recipe:edit??r,key:`${r.id}:large`}] as const
        for(const item of items){const target=canvases.current.get(item.key);if(!target||!target.isConnected||(!visible.current.has(item.key)&&drawn.current.has(item.key)))continue;const small=item.key.endsWith(':small'),mobile=innerWidth<=767;if(playing&&tick%2===1&&small)continue;let scene=sceneCache.current.get(JSON.stringify(item.recipe));if(!scene){scene=compile(item.recipe);sceneCache.current.set(JSON.stringify(item.recipe),scene);if(sceneCache.current.size>8)sceneCache.current.delete(sceneCache.current.keys().next().value!)}
          const time=previewTime.current
          const output=await p.render(scene,time,small&&mobile?320:480);target.width=480;target.height=Math.round(480*scene.height/scene.width);target.getContext('2d')!.drawImage(output,0,0,target.width,target.height);drawn.current.add(item.key)}
        if(playing)tick=(tick+1)%180
      }catch(e){setError(String(e))}finally{working=false}}
    raf=requestAnimationFrame(loop);return()=>{live=false;cancelAnimationFrame(raf);p.remove();if(host.current===p)host.current=null}
  },[ready,playing,panel,busy,edit])
  async function prepare(recipes:Recipe[]){for(const r of recipes){await loadFonts(r);compile(r)}}
  async function generateNew(){if(busy||editing)return;let brief;try{brief=validateBrief(draftTitle,draftSubtitle)}catch(e){setError(String(e));return}const id=++generation.current;setBusy('4案を作っています…');setError('');try{const start=(dataRef.current.exploreCounter*4+9)%families.length;const next=explore(brief,draftFormat,draftFilter,randomSeed(),start);await prepare(next);if(id!==generation.current)return;update(s=>{const current=s.boards.find(b=>b.id===s.activeBoardId)!;const b=board(next,'explore',current,null,draftFilter);return{...s,boards:appendBoard(s.boards,b),activeBoardId:b.id,exploreCounter:s.exploreCounter+1}});setNotice('4案を差し替えました。')}catch(e){setError(String(e))}finally{setBusy('')}}
  async function generateNear(){if(busy||editing||dirty||domains.every(k=>active.locks[k]))return;const id=++generation.current;setBusy('近い案を作っています…');setError('');try{const result=refine(selected,active.locks,randomSeed());if(!result.recipes.length){setNotice('条件に合う別案は0件です。');return}await prepare(result.recipes);if(id!==generation.current)return;update(s=>{const current=s.boards.find(b=>b.id===s.activeBoardId)!;const b=board(result.recipes,'refine',current,selected.id,current.filter,result.labels);return{...s,boards:appendBoard(s.boards,b),activeBoardId:b.id}});setNotice(result.recipes.length<4?`条件に合う別案は${result.recipes.length}件です。`:'元の案から4案を作りました。')}catch(e){setError(String(e))}finally{setBusy('')}}
  function choose(id:string){if(editing||busy)return;update(s=>({...s,boards:s.boards.map(b=>b.id===s.activeBoardId?{...b,selectedId:id}:b)}));const r=active.candidates.find(x=>x.id===id)!;setDraftTitle(r.brief.title);setDraftSubtitle(r.brief.subtitle);setDraftFormat(r.format);setNotice(`${familyNames[r.family]}・${compositionNames[r.shape.composition]}を選択しました。`)}
  function setLock(key:Domain,value:boolean){update(s=>({...s,boards:s.boards.map(b=>b.id===s.activeBoardId?{...b,locks:{...b.locks,[key]:value}}:b)}))}
  function restore(id:string){if(editing||busy)return;const b=data.boards.find(x=>x.id===id);if(!b)return;update(s=>({...s,activeBoardId:id}));const r=b.candidates.find(x=>x.id===b.selectedId)!;setDraftTitle(r.brief.title);setDraftSubtitle(r.brief.subtitle);setDraftFormat(r.format);setDraftFilter(b.filter);closePanel();setNotice('候補と固定を復元しました。')}
  function toggleFavorite(recipe:Recipe){const key=canonical(recipe),existing=data.favorites.find(x=>canonical(x)===key);if(!existing&&data.favorites.length>=50){setError('お気に入りは50件までです。');return}update(s=>({...s,favorites:existing?s.favorites.filter(x=>canonical(x)!==key):[...s.favorites,recipe]}));if(existing)setRemovedFavorite(existing);else setRemovedFavorite(null);setNotice(existing?'お気に入りを外しました。':'お気に入りに保存しました。')}
  function applyEdit(){if(!edit)return;try{compile(edit);update(s=>{const current=s.boards.find(b=>b.id===s.activeBoardId)!;const b=board([{...edit,id:crypto.randomUUID()}],'edit',current,selected.id,current.filter);return{...s,boards:appendBoard(s.boards,b),activeBoardId:b.id}});setEdit(null);setNotice('調整を適用しました。')}catch(e){setError(String(e))}}
  function adjust(domain:Domain,value:string){if(!edit)return;const r:Recipe={...edit,id:edit.id,color:{...edit.color},type:{...edit.type},shape:{...edit.shape},motion:{...edit.motion}};if(domain==='color'){const id=value as PaletteId;const p=palettes[id];r.color={paletteId:id,...p}}
    if(domain==='type'){if(value==='sans'||value==='serif')r.type.fontId=value==='sans'?'noto-sans-jp-700':'noto-serif-jp-600';else if(value==='left'||value==='center')r.type.align=value;else r.type.size=value as Recipe['type']['size']}
    if(domain==='shape'){if(['low','medium','high'].includes(value))r.shape.density=value as Recipe['shape']['density'];else r.shape.composition=value}
    if(domain==='motion')r.motion.amount=value as Recipe['motion']['amount'];setEdit(r)}
  function refreshCapabilities(recipe:Recipe,nextSize:720|1080){const request=++capabilityRequest.current;setKinds([]);setKind(null);capabilities(recipe,nextSize).then(v=>{if(request===capabilityRequest.current){setKinds(v);setKind(v[0]??null)}}).catch(e=>{if(request===capabilityRequest.current)setError(String(e))})}
  function openPanel(next:'export'|'history'|'favorites'){setPanel(next);dialogRef.current?.showModal();if(next==='export'){setVideoBlob(null);setProgress(0);refreshCapabilities(selected,size)}}
  function closePanel(){if(busy.startsWith('動画'))return;dialogRef.current?.close();setPanel(null);setVideoBlob(null)}
  async function exportPng(){setBusy('PNGを作っています…');setError('');try{const blob=await png(selected,frame);saveBlob(blob,`moving-cover-${selected.id.slice(0,8)}.png`);setNotice('PNGを作成しました。')}catch(e){setError(String(e))}finally{setBusy('')}}
  async function exportVideo(){if(!kind)return;const frozen=structuredClone(selected),chosen=kind;cancelExport.current=false;setBusy('動画を書き出しています…');setProgress(0);setVideoBlob(null);setError('');const slowTimer=setTimeout(()=>setNotice('処理に時間がかかっています。キャンセルできます。'),30000);try{const blob=await video(frozen,size,chosen,n=>setProgress(n),()=>cancelExport.current);if(blob){setVideoKind(chosen);setVideoBlob(blob);setNotice('動画ができました。再生を確認して保存できます。')}else setNotice('動画をキャンセルしました。')}catch(e){setError(`動画を作れませんでした: ${String(e)}`)}finally{clearTimeout(slowTimer);setBusy('')}}
  async function readJson(file:File){try{const r=await importJson(file);await prepare([r]);update(s=>{const current=s.boards.find(b=>b.id===s.activeBoardId)!;const b=board([r],'import',current,null,current.filter);b.locks=emptyLocks();return{...s,boards:appendBoard(s.boards,b),activeBoardId:b.id}});setDraftTitle(r.brief.title);setDraftSubtitle(r.brief.subtitle);setDraftFormat(r.format);setNotice('JSONから作品を読み込みました。')}catch(e){setError(`JSONを読み込めません: ${String(e)}`)}}
  const favorite=data.favorites.some(x=>canonical(x)===canonical(selected)),parent=active.parentBoardId&&data.boards.find(b=>b.id===active.parentBoardId)
  return <div className="app-shell"><header><div><span className="masthead">MOVING COVER STUDIO / 09.25</span><h1>動く表紙の試着室</h1><p>言葉を着せ替えて、動く表紙に。</p></div><nav><button onClick={()=>openPanel('history')}><History size={18}/>履歴</button><button onClick={()=>openPanel('favorites')}><Heart size={18}/>お気に入り</button></nav></header>
    <main><section className="brief" aria-label="表紙の言葉"><div className="brief-fields"><label>タイトル<textarea value={draftTitle} rows={2} onChange={e=>{generation.current++;setDraftTitle(e.target.value)}}/></label><label>補助テキスト（任意）<input value={draftSubtitle} onChange={e=>{generation.current++;setDraftSubtitle(e.target.value)}}/></label><label>比率<select value={draftFormat} onChange={e=>{generation.current++;setDraftFormat(e.target.value as 'square'|'portrait')}}><option value="square">正方形</option><option value="portrait">縦長</option></select></label></div><fieldset className="style-picker"><legend>表現を選ぶ</legend><p>見本は「動く 言葉」。あなたの文字で4案を作ります。</p><div className="style-options"><button type="button" className="style-option" aria-pressed={draftFilter==='all'} onClick={()=>{generation.current++;setDraftFilter('all')}}><span className="style-mix" aria-hidden="true">{(['monolith','interference','scatter'] as Family[]).map(f=><img key={f} src={`./style-previews/${f}.webp`} alt=""/>)}</span><span className="style-option-copy"><strong>おまかせ</strong><small>12表現から4案</small></span>{draftFilter==='all'&&<span className="style-selected"><Check size={15}/>選択中</span>}</button>{styleOrder.map(f=><button key={f} type="button" className="style-option" aria-pressed={draftFilter===f} onClick={()=>{generation.current++;setDraftFilter(f)}}><img src={`./style-previews/${f}.webp`} alt=""/><span className="style-option-copy"><strong>{familyNames[f]}</strong><small>{styleDescriptions[f]}</small></span>{draftFilter===f&&<span className="style-selected"><Check size={15}/>選択中</span>}</button>)}</div></fieldset><button className="primary generate-button" onClick={generateNew} disabled={!!busy||editing}>4案を見る <span>{draftFilter==='all'?'12表現から探す':`${familyNames[draftFilter]}で探す`}</span></button></section>
    {!ready&&<p className="status" role="status">文字と作品を準備しています… {error&&<button onClick={()=>location.reload()}>再試行</button>}</p>}{dirty&&<p className="status">入力に変更があります。4案を見ると反映されます。</p>}{busy&&<p className="status" role="status">{busy}</p>}{error&&<p className="error" role="alert">{error} {conflicted.current&&<button onClick={()=>location.reload()}>最新を読み込む</button>}{allowReset&&<button onClick={async()=>{await clearSavedState();location.reload()}}>新しく始める</button>}</p>}{notice&&<p className="status" role="status">{notice}</p>}{removedFavorite&&<p className="status">お気に入りを外しました。<button onClick={()=>{const saved=removedFavorite;update(s=>({...s,favorites:[...s.favorites,saved]}));setRemovedFavorite(null)}}>取り消す</button></p>}
    <div className="workspace"><section className="candidates"><div className="section-heading"><h2>候補を比べる</h2><span>{active.candidates.length}案</span></div><div className="candidate-grid">{active.candidates.map((r,i)=><article key={r.id} className={r.id===selected.id?'candidate chosen':'candidate'}><button className="candidate-select" onClick={()=>choose(r.id)} disabled={editing||!!busy} aria-pressed={r.id===selected.id}><Cover recipe={r} register={register}/><strong>{String.fromCharCode(65+i)}. {familyNames[r.family]}・{compositionNames[r.shape.composition]}</strong><small>{active.labels?.[i]??`${r.color.paletteId} / ${r.type.fontId.includes('serif')?'明朝':'ゴシック'}`}</small></button><button className="favorite-mini" aria-label={`${String.fromCharCode(65+i)}をお気に入り${data.favorites.some(x=>canonical(x)===canonical(r))?'から外す':'に入れる'}`} onClick={()=>toggleFavorite(r)}><Star size={17} fill={data.favorites.some(x=>canonical(x)===canonical(r))?'currentColor':'none'}/></button></article>)}</div></section>
    <section className="inspector" id="selected"><div className="section-heading"><h2>選択中の表紙</h2><button onClick={()=>setPlaying(v=>!v)}><>{playing?<Pause size={16}/>:<Play size={16}/>}</>{playing?'停止':'再生'}</button></div><div className="preview-wrap"><Cover recipe={shown} large register={register}/></div><p className="selected-name">{familyNames[shown.family]}・{compositionNames[shown.shape.composition]} / {shown.brief.title}</p><div className="locks"><p>残したい部分を固定</p><div>{domains.map(k=><label key={k}><input type="checkbox" checked={active.locks[k]} onChange={e=>setLock(k,e.target.checked)} disabled={editing||!!busy}/><LockKeyhole size={14}/>{domainNames[k]}</label>)}</div></div><div className="actions"><button className="primary" onClick={generateNear} disabled={!!busy||editing||dirty||domains.every(k=>active.locks[k])}>この案から4案</button><button onClick={()=>toggleFavorite(selected)} disabled={editing||!!busy}><Star size={17} fill={favorite?'currentColor':'none'}/>{favorite?'お気に入り済み':'お気に入り'}</button></div>{domains.every(k=>active.locks[k])&&<p className="hint">変えたい項目の固定を外してください。</p>}
      <details open={editing} onToggle={e=>{if((e.currentTarget as HTMLDetailsElement).open){if(!edit)setEdit(structuredClone(selected))}else if(edit){setEdit(null);setNotice('未適用の調整を取り消しました。')}}}><summary>調整する</summary><p className="hint">固定は別案を作るときに適用されます。</p><div className="adjust-grid"><label>色<select value={shown.color.paletteId} onChange={e=>adjust('color',e.target.value)}>{Object.keys(palettes).map(v=><option key={v}>{v}</option>)}</select></label><label>書体<select value={shown.type.fontId.includes('serif')?'serif':'sans'} onChange={e=>adjust('type',e.target.value)}><option value="sans">ゴシック</option><option value="serif">明朝</option></select></label><label>整列<select value={shown.type.align} onChange={e=>adjust('type',e.target.value)}><option value="left">左</option><option value="center">中央</option></select></label><label>文字サイズ<select value={shown.type.size} onChange={e=>adjust('type',e.target.value)}><option value="small">小</option><option value="medium">標準</option><option value="large">大</option></select></label><label>構図<select value={shown.shape.composition} onChange={e=>adjust('shape',e.target.value)}>{compositions[shown.family].map(v=><option key={v} value={v}>{compositionNames[v]}</option>)}</select></label><label>密度<select value={shown.shape.density} onChange={e=>adjust('shape',e.target.value)}><option value="low">少なめ</option><option value="medium">標準</option><option value="high">多め</option></select></label><label>動き<select value={shown.motion.amount} onChange={e=>adjust('motion',e.target.value)}><option value="calm">静か</option><option value="normal">標準</option><option value="bold">大きく</option></select></label></div><div className="actions"><button onClick={applyEdit} disabled={!edit}>調整を適用</button><button onClick={()=>setEdit(null)}>取り消す</button></div></details>
      <div className="bottom-actions"><button onClick={()=>parent&&restore(parent.id)} disabled={!parent||editing||!!busy}><ArrowLeft size={17}/>ひとつ前の候補へ</button><button className="primary" onClick={()=>openPanel('export')} disabled={editing||!!busy}><Download size={17}/>書き出す</button></div><p className="save-status">{saveStatus} / この端末のブラウザに保存</p></section></div></main>
      <dialog ref={dialogRef} onClose={()=>setPanel(null)} onCancel={e=>{if(busy.startsWith('動画'))e.preventDefault()}}><div className="dialog-top"><h2>{panel==='export'?'書き出す':panel==='history'?'履歴':'お気に入り'}</h2><button aria-label="閉じる" onClick={closePanel} disabled={busy.startsWith('動画')}><X size={20}/></button></div>{panel==='export'&&<div className="dialog-body"><p>「{selected.brief.title}」を持ち帰る</p><label>PNGのフレーム {frame}/179<input type="range" min="0" max="179" value={frame} onChange={e=>setFrame(Number(e.target.value))}/></label><div className="actions"><button onClick={exportPng} disabled={!!busy}>PNG 1080px</button><button onClick={()=>saveBlob(projectJson(selected),`moving-cover-${selected.id.slice(0,8)}.json`)}>再編集用JSON</button></div><hr/><label>動画のサイズ<select value={size} disabled={!!busy} onChange={e=>{const n=Number(e.target.value) as 720|1080;setSize(n);refreshCapabilities(selected,n)}}><option value="720">標準 720px</option><option value="1080">高画質 1080px</option></select></label><label>動画形式<select value={kind??''} onChange={e=>setKind(e.target.value as VideoKind)} disabled={!kinds.length||!!busy}>{kinds.length?kinds.map(v=><option key={v} value={v}>{v==='mp4'?'MP4 / AVC':v==='webm-vp9'?'WebM / VP9':'WebM / VP8'}</option>):<option value="">動画非対応</option>}</select></label><p>6秒・30fps・無音。端末内で作成します。</p>{kind?<button className="primary" onClick={exportVideo} disabled={!!busy}>動画を作る</button>:<p className="hint">この環境では動画を作れません。PNGとJSONを利用できます。</p>}{busy.startsWith('動画')&&<><p role="status">{progress}/180フレーム {progress===180?'最終処理中…':''}</p><progress value={progress} max={180}/><button onClick={()=>{cancelExport.current=true}}>キャンセル</button></>}{videoBlob&&videoUrl&&<><video className="export-preview" src={videoUrl} controls playsInline aria-label="生成した動画の再生確認"/><button className="primary" onClick={()=>saveBlob(videoBlob,`moving-cover-${selected.id.slice(0,8)}.${videoKind==='mp4'?'mp4':'webm'}`)}>動画を保存</button></>}</div>}
      {panel==='history'&&<div className="dialog-body list">{[...data.boards].reverse().map(b=><button key={b.id} onClick={()=>restore(b.id)} disabled={editing||!!busy}><span>{b.operation} / {new Date(b.createdAt).toLocaleString('ja-JP')}</span><strong>{b.candidates.find(r=>r.id===b.selectedId)?.brief.title}</strong></button>)}</div>}
      {panel==='favorites'&&<div className="dialog-body list">{!data.favorites.length?<p>お気に入りはまだありません。</p>:data.favorites.map(r=><button key={r.id} onClick={()=>{const b=board([r],'favorite',active,r.id,active.filter);b.locks=emptyLocks();update(s=>({...s,boards:appendBoard(s.boards,b),activeBoardId:b.id}));setDraftTitle(r.brief.title);setDraftSubtitle(r.brief.subtitle);setDraftFormat(r.format);closePanel()}}><strong>{r.brief.title}</strong><span>この作品で続ける</span></button>)}</div>}</dialog><input ref={fileRef} type="file" accept="application/json,.json" hidden onChange={e=>{const f=e.target.files?.[0];if(f)readJson(f);e.target.value=''}}/><footer><button onClick={()=>fileRef.current?.click()}>JSONを読み込む</button><span>入力と作品は端末内で処理します。 <a href="./THIRD_PARTY_NOTICES.md">ライセンス</a></span></footer></div>
}
