version: 2
updates:
  - package-ecosystem: npm
    directory: /2026-09-01
    schedule:
      interval: weekly
    groups:
      frontend-dependencies:
        patterns:
          - '*'
  - package-ecosystem: npm
    directory: /2026-09-02
    schedule:
      interval: weekly
    groups:
      frontend-dependencies:
        patterns:
          - '*'
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
