import { test, expect } from '@playwright/test'
import { mkdir, readFile } from 'node:fs/promises'
const artifact='docs/verification/artifacts'
async function shortProject(){const p=JSON.parse(await readFile('src/celestial.project.json','utf8'));p.id=crypto.randomUUID();p.name='再出力テスト';return p}
test('responsive editing and JSON recovery',async({page})=>{
  for(const width of [375,768,1024,1440]){
    await page.setViewportSize({width,height:900});await page.goto('/');await expect(page.getByRole('heading',{name:'Type Motion Studio'})).toBeVisible();await expect(page.getByLabel('映像プレビュー')).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth+2)).toBe(true);await mkdir(artifact,{recursive:true});await page.screenshot({path:`${artifact}/ui-${width}.png`});if(width===375){await page.getByRole('button',{name:'文章',exact:true}).click();await expect(page.getByLabel('一行一場面で入力')).toBeVisible();await page.getByRole('button',{name:'調整',exact:true}).click();await expect(page.getByRole('textbox',{name:'見出し'})).toBeVisible();await page.getByRole('button',{name:'場面',exact:true}).click()}
  }
  await page.setViewportSize({width:1440,height:900});await page.reload();await page.getByLabel('一行一場面で入力').fill('ひらめきを\n動かそう\n言葉が、映像になる');await page.getByRole('button',{name:'映像を組む'}).click();await expect(page.getByText('言葉が、映像になる').first()).toBeVisible();await page.getByRole('button',{name:'Undo'}).click();await expect(page.getByRole('button',{name:/THINK BEYOND/}).first()).toBeVisible();await page.getByRole('button',{name:'Redo'}).click();await expect(page.getByText('言葉が、映像になる').first()).toBeVisible();const downloadPromise=page.waitForEvent('download');await page.getByRole('button',{name:'JSONで退避'}).click();const download=await downloadPromise;await download.saveAs(`${artifact}/japanese-project.json`);await expect(page.getByText('保存済み')).toBeVisible();await page.reload();await expect(page.getByText('言葉が、映像になる').first()).toBeVisible();await page.locator('input[type=file]').setInputFiles(`${artifact}/japanese-project.json`);await expect(page.getByText('JSONを別作品として読み込みました')).toBeVisible();await page.locator('input[type=file]').setInputFiles({name:'bad.json',mimeType:'application/json',buffer:Buffer.from('{bad')});await expect(page.getByText(/JSONを読み込めません/)).toBeVisible();await expect(page.getByText('言葉が、映像になる').first()).toBeVisible()
})
test('cancel and retry actual MP4',async({page})=>{
  await page.goto('/');const data=Buffer.from(JSON.stringify(await shortProject()));await page.locator('input[type=file]').setInputFiles({name:'short.json',mimeType:'application/json',buffer:data});await expect(page.getByText('24.0 SEC')).toBeVisible();await page.getByRole('button',{name:'動画を書き出す'}).click();await expect(page.getByRole('button',{name:'中止'})).toBeVisible();await page.getByRole('button',{name:'中止'}).click({force:true});await expect(page.getByText('書き出しを中止しました。再試行できます')).toBeVisible();const downloadPromise=page.waitForEvent('download',{timeout:120000});await page.getByRole('button',{name:'動画を書き出す'}).click();const download=await downloadPromise;await download.saveAs(`${artifact}/short-retry.mp4`);await expect(page.getByText(/MP4を書き出しました/)).toBeVisible()
})

test('seek produces the same frame after scene jumps',async({page})=>{await page.goto('/');await page.getByRole('button',{name:/02 ASTRA/}).first().click();const a=await page.locator('canvas').evaluate(el=>(el as HTMLCanvasElement).toDataURL());await page.getByRole('button',{name:/04 LUNA/}).first().click();await page.getByRole('button',{name:/02 ASTRA/}).first().click();const b=await page.locator('canvas').evaluate(el=>(el as HTMLCanvasElement).toDataURL());expect(b).toBe(a)})
test('three composition recipes produce distinct moving scenes',async({page})=>{
  const frames:string[]=[]
  page.on('dialog',dialog=>dialog.accept())
  for(const recipe of ['celestial','manifesto','rhythm']){
    await page.goto('/');await page.getByLabel('一行一場面で入力').fill('はじまり\n星 太陽 月\n光の話\n影の話\n色 形 音\nおわり');await page.getByRole('combobox',{name:'構成レシピ'}).selectOption(recipe);await page.getByRole('button',{name:'映像を組む'}).click();await expect(page.locator('.scene-list button').nth(1)).toContainText(({celestial:'粒子と接近',manifesto:'帯と軌道',rhythm:'三分割'} as Record<string,string>)[recipe]);await page.getByRole('button',{name:/02 星 太陽 月/}).first().click();await page.getByRole('button',{name:'再生',exact:true}).click();await page.waitForTimeout(750);await page.getByRole('button',{name:'一時停止'}).click();frames.push(await page.locator('canvas').evaluate(el=>(el as HTMLCanvasElement).toDataURL()));await page.screenshot({path:`${artifact}/recipe-${recipe}.png`})
  }
  expect(new Set(frames).size).toBe(3)
})
test('circle match changes duration and keeps one shared circle',async({page})=>{
  await page.goto('/');await page.getByRole('button',{name:/03 SOL/}).first().click();await page.getByRole('combobox',{name:'次場面へのつなぎ'}).selectOption('circle-match');await expect(page.locator('.preview-head span')).toContainText('23.5 SEC');await page.getByRole('button',{name:/04 LUNA/}).first().click();await page.screenshot({path:`${artifact}/circle-match-start.png`});await page.getByRole('button',{name:'再生',exact:true}).click();await page.waitForTimeout(300);await page.getByRole('button',{name:'一時停止'}).click();await page.screenshot({path:`${artifact}/circle-match-middle.png`});await page.getByRole('button',{name:'Undo'}).click();await expect(page.locator('.preview-head span')).toContainText('24.0 SEC')
})
