import { build } from 'esbuild'
import { readFile, writeFile } from 'node:fs/promises'
const result=await build({entryPoints:['src/player/entry.ts'],bundle:true,format:'iife',target:'es2022',minify:true,write:false})
const script=result.outputFiles[0].text
const latin=(await readFile('public/fonts/SpaceGrotesk.ttf')).toString('base64')
const japanese=(await readFile('public/fonts/noto-sans-jp-japanese-700-normal.woff2')).toString('base64')
const licenses=(await Promise.all(['public/fonts/OFL.txt','public/fonts/Noto-LICENSE.txt'].map(file=>readFile(file,'utf8')))).join('\n\n')
await writeFile('src/export/player-bundle.ts',`// Generated by scripts/build-player.mjs\nexport const playerScript=${JSON.stringify(script)}\nexport const latinFont=${JSON.stringify(latin)}\nexport const japaneseFont=${JSON.stringify(japanese)}\nexport const fontLicenses=${JSON.stringify(licenses)}\n`)
