import type { Project } from '../domain/project'
import { parseProject } from '../domain/project'
import { fontLicenses, japaneseFont, latinFont, playerScript } from './player-bundle'
export function standaloneHtml(project:Project){
  const p=parseProject(project),json=JSON.stringify(p).replaceAll('&','\\u0026').replaceAll('<','\\u003c').replaceAll('>','\\u003e').replaceAll('\u2028','\\u2028').replaceAll('\u2029','\\u2029')
  const fonts=`@font-face{font-family:MotionLatin;src:url(data:font/ttf;base64,${latinFont}) format('truetype');font-weight:300 700;font-display:block}@font-face{font-family:MotionJapanese;src:url(data:font/woff2;base64,${japaneseFont}) format('woff2');font-weight:700;font-display:block}`
  return `<!doctype html><html lang="ja"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Type Motion Film</title><style>${fonts}*{box-sizing:border-box}body{margin:0;background:#111115;color:#f4f0e7;font:16px system-ui,sans-serif}main{max-width:1200px;margin:auto;padding:24px}canvas{display:block;width:100%;max-height:80vh;object-fit:contain;background:#111115;border:2px solid #f4f0e7}nav{display:flex;gap:8px;flex-wrap:wrap;margin-top:16px;align-items:center}button{border:2px solid #f4f0e7;background:#f4f0e7;color:#111115;padding:12px 16px;font:inherit;cursor:pointer}input[type=range]{flex:1;min-width:160px}button:focus-visible,input:focus-visible{outline:3px solid #ff7345;outline-offset:2px}</style></head><body><main><canvas id="film" aria-label="モーショングラフィック"></canvas><nav><button id="play">再生</button><button id="replay">最初から</button><input id="seek" type="range" min="0" step="0.01" value="0" aria-label="再生位置"><output id="time"></output><button id="sound">音 OFF</button><button id="fullscreen">全画面</button></nav><p id="status">準備中…</p></main><script id="project-data" type="application/json">${json}</script><script>${playerScript}</script><!-- ${fontLicenses.replaceAll('-->','--&gt;')} --></body></html>`
}
export function htmlBlob(p:Project){return new Blob([standaloneHtml(p)],{type:'text/html'})}
